"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-09-13 04:47:09.023041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('fy_start_month', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('short_name', sa.String(length=60), nullable=True),
    sa.Column('owner_phone', sa.String(length=30), nullable=True),
    sa.Column('owner_email', sa.String(length=200), nullable=True),
    sa.Column('accountant_email', sa.String(length=200), nullable=True),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_days_before', sa.JSON(), nullable=True),
    sa.Column('weekly_digest_day', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('default_cycle', sa.String(length=20), nullable=False),
    sa.Column('variable', sa.Boolean(), nullable=False),
    sa.Column('prepaid', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('is_reseller', sa.Boolean(), nullable=False),
    sa.Column('sells', sa.JSON(), nullable=True),
    sa.Column('pay_url', sa.String(length=300), nullable=True),
    sa.Column('exclude', sa.Boolean(), nullable=False),
    sa.Column('intro_pricing', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('bank_name', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_company_id'), 'accounts', ['company_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_company_id'), 'events', ['company_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memberships_company_id'), 'memberships', ['company_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('stream_key', sa.String(length=200), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('vendor_name', sa.String(length=120), nullable=False),
    sa.Column('payee_name', sa.String(length=200), nullable=True),
    sa.Column('product', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('stream_type', sa.String(length=15), nullable=False),
    sa.Column('cycle', sa.String(length=15), nullable=False),
    sa.Column('cycle_months', sa.Float(), nullable=True),
    sa.Column('expected_amount', sa.Float(), nullable=True),
    sa.Column('avg_amount', sa.Float(), nullable=True),
    sa.Column('last_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('last_paid_date', sa.Date(), nullable=True),
    sa.Column('next_due', sa.Date(), nullable=True),
    sa.Column('anchor_day', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('paid_from', sa.String(length=120), nullable=True),
    sa.Column('owner_name', sa.String(length=80), nullable=True),
    sa.Column('pay_url', sa.String(length=300), nullable=True),
    sa.Column('reminder_on', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('amount_history', sa.JSON(), nullable=False),
    sa.Column('is_user_modified', sa.Boolean(), nullable=False),
    sa.Column('user_fields', sa.JSON(), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('occurrences_count', sa.Integer(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streams_company_id'), 'streams', ['company_id'], unique=False)
    op.create_index(op.f('ix_streams_status'), 'streams', ['status'], unique=False)
    op.create_index(op.f('ix_streams_stream_key'), 'streams', ['stream_key'], unique=False)
    op.create_table('vendor_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('product', sa.String(length=120), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_aliases_company_id'), 'vendor_aliases', ['company_id'], unique=False)
    op.create_index(op.f('ix_vendor_aliases_vendor_id'), 'vendor_aliases', ['vendor_id'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source_kind', sa.String(length=20), nullable=False),
    sa.Column('detected_format', sa.String(length=80), nullable=True),
    sa.Column('rows_imported', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_company_id'), 'import_batches', ['company_id'], unique=False)
    op.create_table('occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('payee_clean', sa.String(length=200), nullable=False),
    sa.Column('product', sa.String(length=120), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('amount_gross', sa.Float(), nullable=False),
    sa.Column('taxable', sa.Float(), nullable=True),
    sa.Column('gst', sa.Float(), nullable=True),
    sa.Column('tds', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fx_amount', sa.Float(), nullable=True),
    sa.Column('payment_mode', sa.String(length=10), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('invoice_no', sa.String(length=80), nullable=True),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('is_personal', sa.Boolean(), nullable=False),
    sa.Column('unpaid', sa.Boolean(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('raw_row_ids', sa.JSON(), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('resolution', sa.String(length=30), nullable=True),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('manual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occurrences_company_id'), 'occurrences', ['company_id'], unique=False)
    op.create_index(op.f('ix_occurrences_date'), 'occurrences', ['date'], unique=False)
    op.create_index(op.f('ix_occurrences_stream_id'), 'occurrences', ['stream_id'], unique=False)
    op.create_index(op.f('ix_occurrences_vendor_id'), 'occurrences', ['vendor_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=15), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('answer', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_answered'), 'questions', ['answered'], unique=False)
    op.create_index(op.f('ix_questions_company_id'), 'questions', ['company_id'], unique=False)
    op.create_index(op.f('ix_questions_key'), 'questions', ['key'], unique=False)
    op.create_table('reminder_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('vendor_name', sa.String(length=120), nullable=False),
    sa.Column('due', sa.Date(), nullable=True),
    sa.Column('channel', sa.String(length=12), nullable=False),
    sa.Column('to', sa.String(length=200), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_log_company_id'), 'reminder_log', ['company_id'], unique=False)
    op.create_index(op.f('ix_reminder_log_stream_id'), 'reminder_log', ['stream_id'], unique=False)
    op.create_table('raw_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fx_amount', sa.Float(), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('payee_clean', sa.String(length=200), nullable=False),
    sa.Column('payment_mode', sa.String(length=10), nullable=True),
    sa.Column('invoice_no', sa.String(length=80), nullable=True),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('taxable', sa.Float(), nullable=True),
    sa.Column('gst', sa.Float(), nullable=True),
    sa.Column('ledger', sa.String(length=120), nullable=True),
    sa.Column('is_personal', sa.Boolean(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_rows_company_id'), 'raw_rows', ['company_id'], unique=False)
    op.create_index(op.f('ix_raw_rows_date'), 'raw_rows', ['date'], unique=False)
    op.create_index(op.f('ix_raw_rows_dedupe_key'), 'raw_rows', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_raw_rows_payee_clean'), 'raw_rows', ['payee_clean'], unique=False)
    op.create_index('ix_rawrow_company_dedupe', 'raw_rows', ['company_id', 'dedupe_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rawrow_company_dedupe', table_name='raw_rows')
    op.drop_index(op.f('ix_raw_rows_payee_clean'), table_name='raw_rows')
    op.drop_index(op.f('ix_raw_rows_dedupe_key'), table_name='raw_rows')
    op.drop_index(op.f('ix_raw_rows_date'), table_name='raw_rows')
    op.drop_index(op.f('ix_raw_rows_company_id'), table_name='raw_rows')
    op.drop_table('raw_rows')
    op.drop_index(op.f('ix_reminder_log_stream_id'), table_name='reminder_log')
    op.drop_index(op.f('ix_reminder_log_company_id'), table_name='reminder_log')
    op.drop_table('reminder_log')
    op.drop_index(op.f('ix_questions_key'), table_name='questions')
    op.drop_index(op.f('ix_questions_company_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_answered'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_occurrences_vendor_id'), table_name='occurrences')
    op.drop_index(op.f('ix_occurrences_stream_id'), table_name='occurrences')
    op.drop_index(op.f('ix_occurrences_date'), table_name='occurrences')
    op.drop_index(op.f('ix_occurrences_company_id'), table_name='occurrences')
    op.drop_table('occurrences')
    op.drop_index(op.f('ix_import_batches_company_id'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_vendor_aliases_vendor_id'), table_name='vendor_aliases')
    op.drop_index(op.f('ix_vendor_aliases_company_id'), table_name='vendor_aliases')
    op.drop_table('vendor_aliases')
    op.drop_index(op.f('ix_streams_stream_key'), table_name='streams')
    op.drop_index(op.f('ix_streams_status'), table_name='streams')
    op.drop_index(op.f('ix_streams_company_id'), table_name='streams')
    op.drop_table('streams')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_company_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_events_company_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_accounts_company_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('companies')
    # ### end Alembic commands ###
